.TH "src/CLIOptions.hpp" 3 "Mon Oct 7 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CLIOptions.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cxxopts/include/cxxopts\&.hpp>\fP
.br
\fC#include <optional>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtsm::cli::CLIOptions\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::cli\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::optional< cxxopts::ParseResult > \fBtsm::cli::parseCmdLineOptions\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBtsm::cli::printHelp\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
