.TH "src/CLIOptions.cpp" 3 "Wed Nov 13 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CLIOptions.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CLIOptions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::cli\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::optional< cxxopts::ParseResult > \fBtsm::cli::parseCmdLineOptions\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBtsm::cli::printHelp\fP ()"
.br
.RI "\fIPrint help message\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
