.TH "src/CommandLine.hpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CommandLine.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Filesystem\&.hpp'\fP
.br
\fC#include <cxxopts/include/cxxopts\&.hpp>\fP
.br
\fC#include <optional>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtsm::CommandLine\fP"
.br
.ti -1c
.RI "struct \fBtsm::CommandLine::Options\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
