.TH "src/CommandLine.cpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CommandLine.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CommandLine\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unordered_set>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBtsm::sanitizeDirectoryPath\fP (const std::string &dirPath)"
.br
.ti -1c
.RI "std::string \fBtsm::cleanRegexPattern\fP (const std::string &inputPattern)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
