.TH "src/CrawlDirectory.hpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CrawlDirectory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Utils/HashString\&.hpp'\fP
.br
\fC#include 'Filesystem\&.hpp'\fP
.br
\fC#include <regex>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBtsm::utils::crawlDirectory\fP (const fs::path &inputDirOrIndexFile, const std::string &regex, const std::string &engine)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
