.TH "src/Database.hpp" 3 "Wed Nov 13 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Database.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'DeletedUniquePtr\&.hpp'\fP
.br
\fC#include 'VariableDesc\&.hpp'\fP
.br
\fC#include <string>\fP
.br
\fC#include <unordered_set>\fP
.br
\fC#include <filesystem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtsm::Database\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::ds\fP"
.br
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
