.TH "src/Database.cpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Database.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Database\&.hpp'\fP
.br
\fC#include 'DatasetDesc\&.hpp'\fP
.br
\fC#include <sqlite3\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unordered_set>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename  = typename std::enable_if_t<std::is_arithmetic_v<T>, T>> auto \fBtsm::toString\fP (const T numeric)"
.br
.RI "Convert numeric value to std::string properly\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
