.TH "src/DatasetDesc.cpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DatasetDesc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'DatasetDesc\&.hpp'\fP
.br
\fC#include 'FileReaders/NCFileReader\&.hpp'\fP
.br
\fC#include 'Utils/ProgressBar\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::ds\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
