.TH "src/FileReaders/FileReader.hpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/FileReaders/FileReader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include '\&.\&./DataFileDesc\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtsm::FileReader< ReaderSubclass >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
