.TH "src/FileReaders/Grib2FileReader.cpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/FileReaders/Grib2FileReader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Grib2FileReader\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
