.TH "src/FileReaders/NCFileReader.cpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/FileReaders/NCFileReader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'NCFileReader\&.hpp'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <ncDim\&.h>\fP
.br
\fC#include <ncVar\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
