.TH "src/Utils/PrettyPrint.hpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Utils/PrettyPrint.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBtsm::utils::bold_on\fP (std::ostream &os)"
.br
.ti -1c
.RI "std::ostream & \fBtsm::utils::bold_off\fP (std::ostream &os)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
