.TH "src/ProgressBar.cpp" 3 "Wed Nov 13 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ProgressBar.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ProgressBar\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::utils\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::size_t \fBLENGTH_OF_PROGRESS_BAR\fP { 55 }"
.br
.ti -1c
.RI "const float \fBPERCENTAGE_BIN_SIZE\fP { 100\&.0/\fBLENGTH_OF_PROGRESS_BAR\fP }"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const std::size_t LENGTH_OF_PROGRESS_BAR { 55 }"

.SS "const float PERCENTAGE_BIN_SIZE { 100\&.0/\fBLENGTH_OF_PROGRESS_BAR\fP }"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
