.TH "std::hash< tsm::ds::VariableDesc >" 3 "Wed Nov 13 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::hash< tsm::ds::VariableDesc > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VariableDesc\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const \fBtsm::ds::VariableDesc\fP &vd) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t std::hash< \fBtsm::ds::VariableDesc\fP >::operator() (const \fBtsm::ds::VariableDesc\fP & vd) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
