.TH "src/TimestampMapper.hpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TimestampMapper.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Filesystem\&.hpp'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include 'CommandLine\&.hpp'\fP
.br
\fC#include 'Database\&.hpp'\fP
.br
\fC#include 'DatasetDesc\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtsm::TimestampMapper\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
