.TH "src/Utils/Timer.hpp" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Utils/Timer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm::utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Func , class\&.\&.\&. Args> auto \fBtsm::utils::timer\fP (Func func, Args &&\&.\&.\&. args) \-> typename std::enable_if_t< !std::is_same_v< decltype(func(std::forward< Args >(args)\&.\&.\&.)), void >, std::pair< double, decltype(func(std::forward< Args >(args)\&.\&.\&.)) > >"
.br
.RI "https://stackoverflow.com/a/24469673/2231969 "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
