.TH "tsm" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBds\fP"
.br
.ti -1c
.RI " \fButils\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandLine\fP"
.br
.ti -1c
.RI "class \fBDatabase\fP"
.br
.ti -1c
.RI "class \fBFileReader\fP"
.br
.ti -1c
.RI "class \fBGrib2FileReader\fP"
.br
.ti -1c
.RI "class \fBNCFileReader\fP"
.br
.ti -1c
.RI "class \fBTimestampMapper\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBsanitizeDirectoryPath\fP (const std::string &dirPath)"
.br
.ti -1c
.RI "std::string \fBcleanRegexPattern\fP (const std::string &inputPattern)"
.br
.ti -1c
.RI "template<typename T , typename  = typename std::enable_if_t<std::is_arithmetic_v<T>, T>> auto \fBtoString\fP (const T numeric)"
.br
.RI "Convert numeric value to std::string properly\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string tsm::cleanRegexPattern (const std::string & inputPattern)"

.SS "auto tsm::sanitizeDirectoryPath (const std::string & dirPath)\fC [inline]\fP"

.SS "template<typename T , typename  = typename std::enable_if_t<std::is_arithmetic_v<T>, T>> auto tsm::toString (const T numeric)"

.PP
Convert numeric value to std::string properly\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
