.TH "tsm::TimestampMapper" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::TimestampMapper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TimestampMapper\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimestampMapper\fP (const \fBCommandLine::Options\fP &opts)"
.br
.ti -1c
.RI "bool \fBexec\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "auto \fBsanitizeDatasetName\fP (const std::string &datasetName) const"
.br
.ti -1c
.RI "auto \fBfileOrDirExists\fP (const fs::path &path) const"
.br
.ti -1c
.RI "bool \fBcreateDirectory\fP (const fs::path &path) const noexcept"
.br
.ti -1c
.RI "std::vector< fs::path > \fBcreateFileList\fP () const"
.br
.ti -1c
.RI "auto \fBshouldDeleteIndexFile\fP () const noexcept"
.br
.ti -1c
.RI "void \fBdeleteIndexFile\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const \fBds::DATASET_TYPE\fP \fBm_datasetType\fP"
.br
.ti -1c
.RI "const \fBCommandLine::Options\fP \fBm_cliOptions\fP"
.br
.ti -1c
.RI "bool \fBm_indexFileExists\fP { false }"
.br
.ti -1c
.RI "\fBDatabase\fP \fBm_database\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tsm::TimestampMapper::TimestampMapper (const \fBCommandLine::Options\fP & opts)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool tsm::TimestampMapper::createDirectory (const fs::path & path) const\fC [private]\fP, \fC [noexcept]\fP"

.SS "std::vector< fs::path > tsm::TimestampMapper::createFileList () const\fC [private]\fP"

.SS "void tsm::TimestampMapper::deleteIndexFile ()\fC [private]\fP"

.SS "bool tsm::TimestampMapper::exec ()"
Runs the tool\&. Returns true on success, false on failure\&. 
.SS "auto tsm::TimestampMapper::fileOrDirExists (const fs::path & path) const\fC [inline]\fP, \fC [private]\fP"

.SS "auto tsm::TimestampMapper::sanitizeDatasetName (const std::string & datasetName) const\fC [inline]\fP, \fC [private]\fP"

.SS "auto tsm::TimestampMapper::shouldDeleteIndexFile () const\fC [inline]\fP, \fC [private]\fP, \fC [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const \fBCommandLine::Options\fP tsm::TimestampMapper::m_cliOptions\fC [private]\fP"

.SS "\fBDatabase\fP tsm::TimestampMapper::m_database\fC [private]\fP"

.SS "const \fBds::DATASET_TYPE\fP tsm::TimestampMapper::m_datasetType\fC [private]\fP"

.SS "bool tsm::TimestampMapper::m_indexFileExists { false }\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
