.TH "tsm::utils" 3 "Wed Nov 13 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::utils \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProgressBar\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T > using \fBdeleted_unique_ptr\fP = std::unique_ptr< T, std::function< void(T *)> >"
.br
.RI "\fITemplate wrapper around a unique_ptr to allow passing a custom deleter lambda\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Func , class\&.\&.\&. Args> auto \fBtimer\fP (Func func, Args &&\&.\&.\&.args) \-> typename std::enable_if_t< !std::is_same_v< decltype(func(std::forward< Args >(args)\&.\&.\&.)), void >, std::pair< double, decltype(func(std::forward< Args >(args)\&.\&.\&.)) > >"
.br
.RI "\fIhttps://stackoverflow.com/a/24469673/2231969 \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "template<typename T > using \fBtsm::utils::deleted_unique_ptr\fP = typedef std::unique_ptr<T, std::function<void(T*)> >"

.PP
Template wrapper around a unique_ptr to allow passing a custom deleter lambda\&. 
.SH "Function Documentation"
.PP 
.SS "template<class Func , class\&.\&.\&. Args> auto tsm::utils::timer (Func func, Args &&\&.\&.\&. args) \-> typename std::enable_if_t<
    !std::is_same_v<decltype( func( std::forward<Args>(args)\&.\&.\&. ) ),
    void>,
    std::pair<double, decltype( func( std::forward<Args>(args)\&.\&.\&. ) ) >
    > \fC [inline]\fP"

.PP
https://stackoverflow.com/a/24469673/2231969 
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
