.TH "tsm::FileReader< ReaderSubclass >" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::FileReader< ReaderSubclass >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileReader\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileReader\fP ()=default"
.br
.ti -1c
.RI "\fB~FileReader\fP ()=default"
.br
.ti -1c
.RI "\fBds::DataFileDesc\fP \fBgetDataFileDesc\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ReaderSubclass> \fBtsm::FileReader\fP< ReaderSubclass >::\fBFileReader\fP ()\fC [default]\fP"

.SS "template<class ReaderSubclass> \fBtsm::FileReader\fP< ReaderSubclass >::~\fBFileReader\fP ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class ReaderSubclass> \fBds::DataFileDesc\fP \fBtsm::FileReader\fP< ReaderSubclass >::getDataFileDesc ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
