.TH "tsm::CommandLine::Options" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::CommandLine::Options
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandLine\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBInputDir\fP"
.br
.ti -1c
.RI "std::string \fBDatasetName\fP"
.br
.ti -1c
.RI "std::string \fBOutputDir\fP"
.br
.ti -1c
.RI "std::string \fBRegexPattern\fP"
.br
.ti -1c
.RI "fs::path \fBFileListPath\fP"
.br
.ti -1c
.RI "std::string \fBRegexEngine\fP"
.br
.ti -1c
.RI "std::vector< fs::path > \fBSTDINfileList\fP"
.br
.ti -1c
.RI "bool \fBDryRun\fP { false }"
.br
.ti -1c
.RI "bool \fBKeepIndexFile\fP { false }"
.br
.ti -1c
.RI "bool \fBRegenIndices\fP { false }"
.br
.ti -1c
.RI "bool \fBForecast\fP { false }"
.br
.ti -1c
.RI "bool \fBHistorical\fP { false }"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string tsm::CommandLine::Options::DatasetName"

.SS "bool tsm::CommandLine::Options::DryRun { false }"

.SS "fs::path tsm::CommandLine::Options::FileListPath"

.SS "bool tsm::CommandLine::Options::Forecast { false }"

.SS "bool tsm::CommandLine::Options::Historical { false }"

.SS "std::string tsm::CommandLine::Options::InputDir"

.SS "bool tsm::CommandLine::Options::KeepIndexFile { false }"

.SS "std::string tsm::CommandLine::Options::OutputDir"

.SS "bool tsm::CommandLine::Options::RegenIndices { false }"

.SS "std::string tsm::CommandLine::Options::RegexEngine"

.SS "std::string tsm::CommandLine::Options::RegexPattern"

.SS "std::vector<fs::path> tsm::CommandLine::Options::STDINfileList"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
