.TH "tsm::Grib2FileReader" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::Grib2FileReader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Grib2FileReader\&.hpp>\fP
.PP
Inherits \fBtsm::FileReader< Grib2FileReader >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGrib2FileReader\fP (const fs::path &path)"
.br
.ti -1c
.RI "\fBds::DataFileDesc\fP \fBgetDataFileDesc_impl\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const fs::path \fBm_path\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tsm::Grib2FileReader::Grib2FileReader (const fs::path & path)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBds::DataFileDesc\fP tsm::Grib2FileReader::getDataFileDesc_impl ()"

.SH "Member Data Documentation"
.PP 
.SS "const fs::path tsm::Grib2FileReader::m_path\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
