.TH "tsm::utils::MM< size, idx, dummy >" 3 "Tue Feb 25 2020" "Version 1.0" "NetCDF Index Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::utils::MM< size, idx, dummy >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HashString\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr unsigned int \fBcrc32\fP (const char *str, unsigned int prev_crc=0xFFFFFFFF)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<int size, int idx = 0, class dummy  = void> static constexpr unsigned int \fBtsm::utils::MM\fP< size, idx, dummy >::crc32 (const char * str, unsigned int prev_crc = \fC0xFFFFFFFF\fP)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Index Tool from the source code\&.
