.TH "tsm::cli::CLIOptions" 3 "Tue Aug 6 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::cli::CLIOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CLIOptions\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLIOptions\fP (const cxxopts::ParseResult &result)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::string \fBInputDir\fP"
.br
.ti -1c
.RI "const std::string \fBDatasetName\fP"
.br
.ti -1c
.RI "const std::string \fBOutputDir\fP"
.br
.ti -1c
.RI "const bool \fBRegenIndices\fP { false }"
.br
.ti -1c
.RI "const bool \fBForecast\fP { false }"
.br
.ti -1c
.RI "const bool \fBHistorical\fP { false }"
.br
.ti -1c
.RI "const bool \fBVarsCombined\fP { false}"
.br
.ti -1c
.RI "const bool \fBVarsSplit\fP { false }"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tsm::cli::CLIOptions::CLIOptions (const cxxopts::ParseResult & result)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const std::string tsm::cli::CLIOptions::DatasetName"

.SS "const bool tsm::cli::CLIOptions::Forecast { false }"

.SS "const bool tsm::cli::CLIOptions::Historical { false }"

.SS "const std::string tsm::cli::CLIOptions::InputDir"

.SS "const std::string tsm::cli::CLIOptions::OutputDir"

.SS "const bool tsm::cli::CLIOptions::RegenIndices { false }"

.SS "const bool tsm::cli::CLIOptions::VarsCombined { false}"

.SS "const bool tsm::cli::CLIOptions::VarsSplit { false }"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
