.TH "tsm::ds::NCFileDesc" 3 "Wed Nov 13 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tsm::ds::NCFileDesc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NCFileDesc\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNCFileDesc\fP (const std::vector< \fBtimestamp_t\fP > &timestamps, const std::vector< \fBVariableDesc\fP > &variables, const std::filesystem::path &path)"
.br
.ti -1c
.RI "\fBNCFileDesc\fP (const \fBNCFileDesc\fP &)=default"
.br
.ti -1c
.RI "\fBNCFileDesc\fP (\fBNCFileDesc\fP &&)=default"
.br
.ti -1c
.RI "\fBNCFileDesc\fP & \fBoperator=\fP (const \fBNCFileDesc\fP &)=default"
.br
.ti -1c
.RI "\fBNCFileDesc\fP & \fBoperator=\fP (\fBNCFileDesc\fP &&)=default"
.br
.ti -1c
.RI "auto \fBoperator!\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::vector< \fBtimestamp_t\fP > \fBTimestamps\fP"
.br
.ti -1c
.RI "const std::vector< \fBVariableDesc\fP > \fBVariables\fP"
.br
.ti -1c
.RI "const std::filesystem::path \fBNCFilePath\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tsm::ds::NCFileDesc::NCFileDesc (const std::vector< \fBtimestamp_t\fP > & timestamps, const std::vector< \fBVariableDesc\fP > & variables, const std::filesystem::path & path)\fC [inline]\fP"

.SS "tsm::ds::NCFileDesc::NCFileDesc (const \fBNCFileDesc\fP &)\fC [default]\fP"

.SS "tsm::ds::NCFileDesc::NCFileDesc (\fBNCFileDesc\fP &&)\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "auto tsm::ds::NCFileDesc::operator! () const\fC [inline]\fP, \fC [noexcept]\fP"

.SS "\fBNCFileDesc\fP& tsm::ds::NCFileDesc::operator= (const \fBNCFileDesc\fP &)\fC [default]\fP"

.SS "\fBNCFileDesc\fP& tsm::ds::NCFileDesc::operator= (\fBNCFileDesc\fP &&)\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const std::filesystem::path tsm::ds::NCFileDesc::NCFilePath"

.SS "const std::vector<\fBtimestamp_t\fP> tsm::ds::NCFileDesc::Timestamps"

.SS "const std::vector<\fBVariableDesc\fP> tsm::ds::NCFileDesc::Variables"


.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
