.TH "src/Database.cpp" 3 "Thu Jul 18 2019" "Version 1.0" "NetCDF Timestamp Mapper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Database.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Database\&.hpp'\fP
.br
\fC#include 'DatasetDesc\&.hpp'\fP
.br
\fC#include <sqlite3\&.h>\fP
.br
\fC#include <boost/format\&.hpp>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtsm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetCDF Timestamp Mapper from the source code\&.
